spring:
  kafka:
    consumer:
      bootstrap-servers: broker:29092
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
