spring:
  config:
    import: optional:configserver:http://root:password@config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-microservices-full
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka