spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: product-service
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka