spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory-service
    username: rashad
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka